# Generated by Django 3.1.3 on 2020-11-15 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='communication',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='engagement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='good_to_work',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='is_public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='knowledge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='points_general',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='support',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='years_experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
