# Generated by Django 3.1.1 on 2020-11-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20201115_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_communication',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_engagement',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_good_to_work',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_knowledge',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_support',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
